# Generated by Django 4.2.4 on 2023-08-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('package_type', models.CharField(choices=[('automatic', 'Automatic'), ('automatic-custom', 'Custom Automatic'), ('text-gen-webui', 'Text Gen Webui'), ('jupyter', 'Jupyter'), ('pytorch', 'Pytorch')], default='jupyter', max_length=255)),
                ('status', models.CharField(choices=[('Starting', 'Starting'), ('Stopping', 'Stopping'), ('Stopped', 'Stopped'), ('Continuing', 'Continuing'), ('Terminating', 'Terminating'), ('Terminated', 'Terminated')], default='Starting', max_length=255)),
                ('additional_params', models.JSONField()),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
