# Generated by Django 4.2.4 on 2023-08-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clusters',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
