# Generated by Django 4.2.4 on 2023-09-04 20:16

from django.db import migrations
from django_celery_beat.models import MINUTES

def create_stop_orphaned_workers_periodic_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')

    schedule = IntervalSchedule.objects.create(every=5, period=MINUTES)
    PeriodicTask.objects.create(
        interval=schedule,
        name='Detecting and stopping orphaned workers',
        task='clusters.worker_tasks.stop_orphaned_workers',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_stop_orphaned_workers_periodic_task, migrations.RunPython.noop),
    ]
