# Generated by Django 4.2.4 on 2023-09-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_cluster_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
