# Generated by Django 4.2.4 on 2023-08-28 14:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_password',
            field=models.CharField(default=accounts.models.generate_service_password, max_length=100),
        ),
    ]
